version: '3.9'

services:
  mongodb:
    image: bitnami/mongodb:5.0.18
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGODB_ADVERTISED_HOSTNAME: '${MONGODB_ADVERTISED_HOSTNAME}'
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_ROOT_USER: '${MONGODB_ROOT_USER}'
      MONGODB_ROOT_PASSWORD: '${MONGODB_ROOT_PASSWORD}'
      MONGODB_REPLICA_SET_KEY: '${MONGODB_REPLICA_SET_KEY}'
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - app-tier
    volumes:
      - 'mongo-db:/bitnami/mongodb'

networks:
  app-tier:
    driver: bridge

volumes:
  mongo-db:
