version: "3.9"

services:
  app:
    build: .
    image: '${TEST_IMAGE}'
    ports:
      - '8080:50051'
    environment:
      RUN: test
      HOST: 'localhost'
      PORT: '50051'
      DATABASE_URL: '${DB_URL}'
      RABBITMQ_HOST: '${RABBITMQ_HOST}'
      RABBITMQ_USERNAME: '${RABBITMQ_USERNAME}'
      RABBITMQ_PASSWORD: '${RABBITMQ_PASSWORD}'
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb-primary:
        condition: service_started
    links:
      - mongodb-primary
      - rabbitmq
    networks:
      - app-tier

  mongodb-primary:
    image: 'bitnami/mongodb:latest'
    environment:
      - MONGODB_ADVERTISED_HOSTNAME='${MONGODB_ADVERTISED_HOSTNAME}'
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD='${MONGODB_ROOT_PASSWORD}'
      - MONGODB_REPLICA_SET_KEY='${MONGODB_REPLICA_SET_KEY}'
    ports:
      - "27017"
    restart: always
    volumes:
      - 'mongodb_master_data:/bitnami'
    networks:
      - app-tier

  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    environment:
      RABBITMQ_USERNAME: '${RABBITMQ_USERNAME}'
      RABBITMQ_PASSWORD: ${RABBITMQ_USERNAME}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5672"
    restart: always
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge

volumes:
  mongodb_master_data:
    driver: local
